/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 room_1.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Room1(props) {
  const { nodes, materials } = useGLTF('/models/room_1/room_1.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane001.geometry} material={materials['Material.004']} position={[1.43, 0, 0]} scale={[2.61, 1, 2.48]} />
      <mesh geometry={nodes.Plane002.geometry} material={materials['Material.004']} position={[-3.77, 0, 0]} rotation={[0, 0, -Math.PI]} scale={[-2.61, -1, -2.48]} />
      <mesh geometry={nodes.Plane003.geometry} material={materials['Material.004']} position={[-8.97, 0, 0]} scale={[2.61, 1, 2.48]} />
      <mesh geometry={nodes.Plane004.geometry} material={materials['Material.004']} position={[-14.19, 0, 0]} rotation={[-Math.PI, 0, 0]} scale={[2.61, 1, 2.48]} />
      <mesh geometry={nodes.Plane005.geometry} material={materials['Material.004']} position={[-19.39, 0, 0]} scale={[2.61, 1, 2.48]} />
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.005']} position={[1.8, 1.07, -1.76]} scale={[2.21, 1.08, 0.71]} />
      <mesh geometry={nodes.Plane006.geometry} material={materials['Material.007']} position={[1.43, 0, -0.01]} scale={[2.61, 1.26, 2.48]} />
      <mesh geometry={nodes.Plane007.geometry} material={materials['Material.007']} position={[-3.77, 0, -0.01]} rotation={[0, 0, -Math.PI]} scale={[-2.61, -1.26, -2.48]} />
      <mesh geometry={nodes.Plane008.geometry} material={materials['Material.007']} position={[-8.97, 0, -0.01]} scale={[2.61, 1.26, 2.48]} />
      <mesh geometry={nodes.Plane009.geometry} material={materials['Material.007']} position={[-14.19, 0, -0.01]} rotation={[-Math.PI, 0, 0]} scale={[2.61, 1.26, 2.48]} />
      <mesh geometry={nodes.Plane010.geometry} material={materials['Material.007']} position={[-19.39, 0, -0.01]} scale={[2.61, 1.26, 2.48]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials['Material.005']} position={[-5.7, 1.07, -1.76]} scale={[2.21, 1.08, 0.71]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials['Material.005']} position={[-10.09, 1.07, -1.76]} scale={[2.21, 1.08, 0.71]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials['Material.005']} position={[-14.48, 1.07, -1.76]} scale={[2.21, 1.08, 0.71]} />
      <mesh geometry={nodes.Cube005.geometry} material={materials['Material.005']} position={[-18.91, 1.07, -1.76]} scale={[2.21, 1.08, 0.71]} />
      <mesh geometry={nodes.Cube006.geometry} material={materials['Material.005']} position={[-23.32, 1.07, -1.76]} scale={[2.21, 1.08, 0.71]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.005']} position={[-5.7, 1.07, 3.06]} rotation={[0, 0, -Math.PI]} scale={[-2.21, -1.08, -0.71]} />
      <mesh geometry={nodes.Cube007.geometry} material={materials['Material.005']} position={[-10.09, 1.07, 3.06]} rotation={[0, 0, -Math.PI]} scale={[-2.21, -1.08, -0.71]} />
      <mesh geometry={nodes.Cube008.geometry} material={materials['Material.005']} position={[-14.48, 1.07, 3.06]} rotation={[0, 0, -Math.PI]} scale={[-2.21, -1.08, -0.71]} />
      <mesh geometry={nodes.Cube009.geometry} material={materials['Material.005']} position={[-18.91, 1.07, 3.06]} rotation={[0, 0, -Math.PI]} scale={[-2.21, -1.08, -0.71]} />
      <mesh geometry={nodes.Cube010.geometry} material={materials['Material.005']} position={[-23.32, 1.07, 3.06]} rotation={[0, 0, -Math.PI]} scale={[-2.21, -1.08, -0.71]} />
      <mesh geometry={nodes.Cube011.geometry} material={materials['Material.005']} position={[-1.33, 1.07, 3.06]} rotation={[0, 0, -Math.PI]} scale={[-2.21, -1.08, -0.71]} />
      <mesh geometry={nodes.Cube012.geometry} material={materials['Material.005']} position={[2.18, 1.07, 3.06]} rotation={[0, 0, -Math.PI]} scale={[-1.37, -1.08, -0.71]} />
      <mesh geometry={nodes.Plane011.geometry} material={materials['Material.004']} position={[1.43, 0, 0]} scale={[2.61, 1, 2.48]} />
      <mesh geometry={nodes.Plane012.geometry} material={materials['Material.004']} position={[-3.77, 0, 0]} rotation={[0, 0, -Math.PI]} scale={[-2.61, -1, -2.48]} />
      <mesh geometry={nodes.Plane013.geometry} material={materials['Material.004']} position={[-8.97, 0, 0]} scale={[2.61, 1, 2.48]} />
      <mesh geometry={nodes.Plane014.geometry} material={materials['Material.004']} position={[-14.19, 0, 0]} rotation={[-Math.PI, 0, 0]} scale={[2.61, 1, 2.48]} />
      <mesh geometry={nodes.Plane015.geometry} material={materials['Material.004']} position={[-19.39, 0, 0]} scale={[2.61, 1, 2.48]} />
      <mesh geometry={nodes.Cube013.geometry} material={materials['Material.007']} position={[2.98, 3.11, 0.64]} scale={[1, 0.36, 3.11]} />
      <mesh geometry={nodes.Cube014.geometry} material={materials['Material.009']} position={[0, 2.83, 0.66]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.75, -0.08, -0.75]} />
      <mesh geometry={nodes.Cube015.geometry} material={materials['Material.009']} position={[0, 2.83, 0.66]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.75, -0.08, -0.75]} />
      <group position={[0.85, 1.03, 2.37]} scale={[0.77, 1.06, 0.08]}>
        <mesh geometry={nodes.Cube019_1.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Cube019_2.geometry} material={materials['Material.015']} />
        <mesh geometry={nodes.Cube019_3.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cube019_4.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Cube019_5.geometry} material={materials['Material.014']} />
      </group>
      <group position={[-3.14, 1.61, -1.44]} rotation={[0, 0, -Math.PI]} scale={-0.25}>
        <mesh geometry={nodes.Cylinder001_1.geometry} material={materials['Material.018']} />
        <mesh geometry={nodes.Cylinder001_2.geometry} material={materials['Material.019']} />
        <mesh geometry={nodes.Cylinder001_3.geometry} material={materials['Material.017']} />
      </group>
      <group position={[-5.42, 1.03, 2.37]} scale={[0.77, 1.06, 0.08]}>
        <mesh geometry={nodes.Cube022_1.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Cube022_2.geometry} material={materials['Material.015']} />
        <mesh geometry={nodes.Cube022_3.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cube022_4.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Cube022_5.geometry} material={materials['Material.014']} />
      </group>
      <group position={[-16.66, 1.03, 2.37]} scale={[0.77, 1.06, 0.08]}>
        <mesh geometry={nodes.Cube025_1.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Cube025_2.geometry} material={materials['Material.015']} />
        <mesh geometry={nodes.Cube025_3.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cube025_4.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Cube025_5.geometry} material={materials['Material.014']} />
      </group>
      <group position={[-22.96, 1.03, 2.37]} scale={[0.77, 1.06, 0.08]}>
        <mesh geometry={nodes.Cube026_1.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Cube026_2.geometry} material={materials['Material.015']} />
        <mesh geometry={nodes.Cube026_3.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cube026_4.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Cube026_5.geometry} material={materials['Material.014']} />
      </group>
      <group position={[-10.66, 1.05, 1.99]} rotation={[0, -0.84, 0]} scale={[0.77, 1.06, 0.08]}>
        <mesh geometry={nodes.Cube027_1.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Cube027_2.geometry} material={materials['Material.015']} />
        <mesh geometry={nodes.Cube027_3.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cube027_4.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Cube027_5.geometry} material={materials['Material.014']} />
      </group>
      <group position={[-11.08, 1.03, 2.37]} rotation={[0, 0, -Math.PI]} scale={[-0.77, -1.06, -0.08]}>
        <mesh geometry={nodes.Cube028.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Cube028_1.geometry} material={materials['Material.015']} />
        <mesh geometry={nodes.Cube028_2.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cube028_3.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Cube028_4.geometry} material={materials['Material.014']} />
      </group>
      <group position={[-22.96, 1.03, -0.57]} rotation={[0, 1.03, -Math.PI]} scale={[-0.77, -1.06, -0.08]}>
        <mesh geometry={nodes.Cube029.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Cube029_1.geometry} material={materials['Material.015']} />
        <mesh geometry={nodes.Cube029_2.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cube029_3.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Cube029_4.geometry} material={materials['Material.014']} />
      </group>
      <group position={[-16.66, 1.03, -1.09]} rotation={[0, 0, -Math.PI]} scale={[-0.77, -1.06, -0.08]}>
        <mesh geometry={nodes.Cube030.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Cube030_1.geometry} material={materials['Material.015']} />
        <mesh geometry={nodes.Cube030_2.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cube030_3.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Cube030_4.geometry} material={materials['Material.014']} />
      </group>
      <group position={[-11.62, 1.03, -1.08]} rotation={[0, 0, -Math.PI]} scale={[-0.77, -1.06, -0.08]}>
        <mesh geometry={nodes.Cube031.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Cube031_1.geometry} material={materials['Material.015']} />
        <mesh geometry={nodes.Cube031_2.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cube031_3.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Cube031_4.geometry} material={materials['Material.014']} />
      </group>
      <group position={[-5.42, 1.03, -0.68]} rotation={[0, 0.67, -Math.PI]} scale={[-0.77, -1.06, -0.08]}>
        <mesh geometry={nodes.Cube032.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Cube032_1.geometry} material={materials['Material.015']} />
        <mesh geometry={nodes.Cube032_2.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cube032_3.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Cube032_4.geometry} material={materials['Material.014']} />
      </group>
      <group position={[-23.14, 1.03, -1.14]} scale={[0.77, 1.06, 0.08]}>
        <mesh geometry={nodes.Cube033.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Cube033_1.geometry} material={materials['Material.015']} />
        <mesh geometry={nodes.Cube033_2.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cube033_3.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Cube033_4.geometry} material={materials['Material.014']} />
      </group>
      <mesh geometry={nodes.Plane019.geometry} material={materials['Material.021']} position={[-2.1, 0.6, 2.1]} rotation={[0, 0, -Math.PI / 2]} scale={[0.16, 0.16, 0.27]} />
      <mesh geometry={nodes.Plane016.geometry} material={materials['Material.021']} position={[-18.98, 0.6, 2.1]} rotation={[0, 0, -Math.PI / 2]} scale={[0.16, 0.16, 0.27]} />
      <mesh geometry={nodes.Plane020.geometry} material={materials['Material.024']} position={[-8.25, 1.37, 2.35]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[0.53, 0.53, 0.69]} />
      <mesh geometry={nodes.Plane021.geometry} material={materials['Material.024']} position={[-20.16, 1.37, -1.04]} rotation={[Math.PI / 2, 0, 0]} scale={[0.65, 0.65, 0.84]} />
      <mesh geometry={nodes.Plane022.geometry} material={materials['Material.023']} position={[1.29, 1.3, -1.04]} rotation={[Math.PI / 2, 0, 0]} scale={[0.67, 0.67, 0.79]} />
      <mesh geometry={nodes.Plane017.geometry} material={materials['Material.027']} position={[-1.93, 1.18, -2.48]} rotation={[Math.PI / 2, 0, 0]} scale={[1.37, 1.18, 1.18]} />
      <group position={[-5.47, 1.03, -1.12]} scale={[0.77, 1.06, 0.08]}>
        <mesh geometry={nodes.Cube036.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Cube036_1.geometry} material={materials['Material.015']} />
        <mesh geometry={nodes.Cube036_2.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cube036_3.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Cube036_4.geometry} material={materials['Material.014']} />
      </group>
      <mesh geometry={nodes.Plane018.geometry} material={materials['Material.021']} position={[-14.25, 0.6, -0.76]} rotation={[0, 0, -Math.PI / 2]} scale={[0.16, 0.16, 0.27]} />
      <group position={[-2.03, 2.73, 0.32]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Circle002.geometry} material={materials['Black.metal']} />
        <mesh geometry={nodes.Circle002_1.geometry} material={materials['Material.029']} />
        <mesh geometry={nodes.Circle002_2.geometry} material={materials['Material.030']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/room_1/room_1.gltf')
